name: Hourly CI/CD Pipeline

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
        
      - name: Run Tests with TestNG
        run: mvn -B test -DsuiteXmlFile=TestSuites/GeneralPrograms.xml
        
      - name: Generate Test Report
        if: success() || failure()
        run: mvn surefire-report:report
        
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/site/
            test-output/
          
  deploy-dev:
    name: Deploy to Development
    needs: build-and-test
    if: github.event_name == 'schedule' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          
      - name: Deploy to Dev Environment
        run: |
          echo "Deploying to development environment..."
          # Add your deployment commands here
          # For example, you might deploy to a test server
          
  deploy-prod:
    name: Deploy to Production
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-reports
          
      - name: Deploy to Production Environment
        run: |
          echo "Deploying to production environment..."
          # Add your production deployment commands here
